import type { Metadata } from 'next'
import { Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import { Geist } from 'next/font/google'
import './globals.css'
import ClerkWrapper from './ClerkProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'welcome to my app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="forced-light">
      <body
        className={
          "antialiased font-sans [&_a]:text-inherit forced-light-mode bg-white text-black transition-colors duration-300"
        }>
        <ClerkWrapper>
          <header className="flex justify-between items-center px-6 py-4">
            {/* Logo / Brand */}
            <div className="text-xl font-bold tracking-tight">☕</div>

            {/* Nav actions — right-aligned */}
            <Show when="signed-out">
              <div className="flex gap-3 items-center">
                <SignInButton />
                <SignUpButton>
                  <button className="btn-primary">Sign Up</button>
                </SignUpButton>
              </div>
            </Show>

            <Show when="signed-in">
              <UserButton />
            </Show>
          </header>
          {children}
        </ClerkWrapper>
      </body>
    </html>
  )
}
